### ISSUE TITLE
NullPointerException when verify called on method using "when" with any() method

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#102]
```
I know this isn't the greatest usage but I'd like the method to return the
same value for any call then verify the correct call was made. 

I do need to verify the parameters but in my case, I'd like the failure to
be obvious (at the validate line) and not implicit (checking for the
correct return value).

I've tried this against 1.8-rc2:
 <dependency>
  <groupId>org.mockito</groupId> 
  <artifactId>mockito-all</artifactId> 
  <version>1.8.0-rc2</version> 
  </dependency>

------------------------------------
-- Example interface (to be mocked):
------------------------------------
public interface Fun {

    public String doFun(String something);

}


------------------------------------
-- Example test: 
------------------------------------

        @Mock private Fun mockFun;
    @Test
    public void testMockitoTest()
    {
        //setup
        when(mockFun.doFun((String)any())).thenReturn("value");

        //do
          mockFun.doFun(null);

        //verify
        verify(mockFun).doFun("hello");

    }


------------------------------------
-- Stack Trace: 
------------------------------------
java.lang.NullPointerException
    at
org.mockito.internal.verification.argumentmatching.ArgumentMatchingTool.toString
Equals(ArgumentMatchingTool.java:48)
    at
org.mockito.internal.verification.argumentmatching.ArgumentMatchingTool.getSuspi
ciouslyNotMatchingArgsIndexes(ArgumentMatchingTool.java:28)
    at
org.mockito.internal.verification.checkers.MissingInvocationChecker.check(Missin
gInvocationChecker.java:38)
    at org.mockito.internal.verification.Times.verify(Times.java:34)
    at org.mockito.internal.MockHandler.intercept(MockHandler.java:74)
    at
org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodIntercepto
rFilter.java:46)
    at impl.Fun$$EnhancerByMockitoWithCGLIB$$40b20f0d.doFun(<generated>)
    at impl.MockitoTest.testMockitoTest(MockitoTest.java:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at
org.junit.internal.runners.TestMethodRunner.executeMethodBody(TestMethodRunner.j
ava:99)
    at
org.junit.internal.runners.TestMethodRunner.runUnprotected(TestMethodRunner.java
:81)
    at
org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunne
r.java:34)
    at
org.junit.internal.runners.TestMethodRunner.runMethod(TestMethodRunner.java:75)
    at org.junit.internal.runners.TestMethodRunner.run(TestMethodRunner.java:45)
    at
org.junit.internal.runners.TestClassMethodsRunner.invokeTestMethod(TestClassMeth
odsRunner.java:71)
    at
org.junit.internal.runners.TestClassMethodsRunner.run(TestClassMethodsRunner.jav
a:35)
    at
org.junit.internal.runners.TestClassRunner$1.runUnprotected(TestClassRunner.java
:42)
    at
org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunne
r.java:34)
    at org.junit.internal.runners.TestClassRunner.run(TestClassRunner.java:52)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReferen
ce.java:45)
    at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:460)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:673)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:386)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:196)





```

Original issue reported on code.google.com by `anthony....@gmail.com` on 30 Jun 2009 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
I'm on it. Thanks a lot for reporting!!!
```

Original comment by `szcze...@gmail.com` on 30 Jun 2009 at 7:17

**Comment by GoogleCodeExporter** [comment]
```
Lame, lame, very lame bug :]. Fixed in trunk. Thanks again for reporting!
```

Original comment by `szcze...@gmail.com` on 9 Jul 2009 at 12:44
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 1:33
- Added labels: **Milestone-Release1.8.1**
