### ISSUE TITLE
ArrayIndexOutOfBoundsException with atLeastOnce() after upgrade to mockito 1.8.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#116]
```
java.lang.ArrayIndexOutOfBoundsException: 0
    at
org.mockito.internal.invocation.InvocationMatcher.captureArgumentsFrom(Invocatio
nMatcher.java:116)
    at
org.mockito.internal.invocation.InvocationMarker.markVerified(InvocationMarker.j
ava:14)
    at
org.mockito.internal.verification.checkers.AtLeastXNumberOfInvocationsChecker.ch
eck(AtLeastXNumberOfInvocationsChecker.java:31)
    at org.mockito.internal.verification.AtLeast.verify(AtLeast.java:38)
    at org.mockito.internal.MockHandler.handle(MockHandler.java:75)
    at
org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodIntercepto
rFilter.java:50)
    at
com.avaloq.commons.ejb.IProgressMonitor$$EnhancerByMockitoWithCGLIB$$f542fa7e.wo
rked(<generated>)
    at
com.avaloq.ice.packager.core.internal.PackagerTest.testCompleteProgress(Packager
Test.java:218)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java
:44)
    at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:
15)
    at
org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:4
1)
    at
org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20
)
    at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70
)
    at
org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:44
)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
    at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
    at
org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReferen
ce.java:46)
    at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:467)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:683)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:390)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:197)


```

Original issue reported on code.google.com by `Knut.Fri...@yahoo.de` on 19 Aug 2009 at 3:18

**Comment by GoogleCodeExporter** [comment]
```
This is the test case:

    /**
     * Tests that {@link Packager#run(long, IProgressMonitor)} reports its
     * progress and checks for cancellation.
     *
     * @throws Exception
     *             should never happen
     */
    @Test
    public void testCompleteProgress() throws Exception {
        IProgressMonitor progressMonitor = mock(IProgressMonitor.class);

        Packager packager = new Packager(packageServices);
        packager.createPackage(BASELINE_ID, progressMonitor);
        verify(progressMonitor).beginTask(anyString(), anyInt());
!!!!        verify(progressMonitor, atLeastOnce()).worked(anyInt());
        verify(progressMonitor, atLeastOnce()).isCanceled();
        verify(progressMonitor).done();
    }

At the marked line the exception occurs.

```

Original comment by `Knut.Fri...@yahoo.de` on 19 Aug 2009 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
When I replace the anyInt() with 1, then the test case works as expected.
```

Original comment by `Knut.Fri...@yahoo.de` on 19 Aug 2009 at 3:24

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting! This is related (e.g. the fix) to issue 112.
```

Original comment by `szcze...@gmail.com` on 22 Aug 2009 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
fixed in trunk. It was related to atLeast() checking code so you can work 
around it
by not using atLeast() in this case.

Thanks again for reporting!
```

Original comment by `szcze...@gmail.com` on 22 Aug 2009 at 8:57

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 22 Aug 2009 at 8:57
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Issue 117 has been merged into this issue.
```

Original comment by `szcze...@gmail.com` on 25 Aug 2009 at 9:04

**Comment by GoogleCodeExporter** [comment]
```
Still fails in latest snapshot---although anyInt() or atMost(n) work fine. The
following line generates an ArrayIndexOutOfBoundsException.

verify(obj, atLeastOnce()).f(anyString());

$ svn info
Path: .
URL: http://mockito.googlecode.com/svn/trunk
Repository Root: http://mockito.googlecode.com/svn
Repository UUID: aa2aecf3-ea3e-0410-9d70-716747e7c967
Revision: 1607
Node Kind: directory
Schedule: normal
Last Changed Author: bbankowski
Last Changed Rev: 1607
Last Changed Date: 2009-08-27 21:23:31 +1000 (Thu, 27 Aug 2009)

Thanks!
```

Original comment by `igor.a.mironov@gmail.com` on 28 Aug 2009 at 5:22

**Comment by GoogleCodeExporter** [comment]
```
oh man, I didn't see your comment. This issue tracker sucks badly.

Will look at it.
```

Original comment by `szcze...@gmail.com` on 15 Sep 2009 at 8:42
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
```
Are you sure you didn't have two mockitoes on classpath? I verified your code 
sample
 works with revision 1587+ ?
```

Original comment by `szcze...@gmail.com` on 15 Sep 2009 at 9:28

**Comment by GoogleCodeExporter** [comment]
```
Thanks for looking into this. Just verified it myself on a clean one-line test 
with
mockito-core 1.8.0 and empty ~/.m2 --- and it compiled/ran without an error!
Indeed it must have been a stray copy of mockito on the classpath or something. 
I'll
try to do a similar clean run of the original test.
```

Original comment by `igor.a.mironov@gmail.com` on 22 Sep 2009 at 12:12

**Comment by GoogleCodeExporter** [comment]
```
Excellent! I'm closing it.
```

Original comment by `szcze...@gmail.com` on 20 Oct 2009 at 7:02
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Issue 129 has been merged into this issue.
```

Original comment by `szcze...@gmail.com` on 28 Oct 2009 at 9:48

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 1:33
- Added labels: **Milestone-Release1.8.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 2:43
- Changed title: **ArrayIndexOutOfBoundsException with atLeastOnce() after upgrade to mockito 1.8.0**

**Comment by GoogleCodeExporter** [comment]
```
Issue 112 has been merged into this issue.
```

Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 2:44
