### ISSUE TITLE
Consider cloning parameters (or only collections) if they are clone'able to avoid mutable args problem

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#126]
```
List<String> list = new ArrayList<String>();
list.add("one");
mock.foo(list);
list.remove("one");
mock.foo(list);
verify(mock).foo(Arrays.asList("one")); // <- throws ArgumentsAreDifferent
verify(mock).foo(Arrays.<String> asList());

Ooops! Mockito seems to store a reference to the list and not make a copy of 
it, so when I change 
the list after the call, the recording that I try to verify is changed.

This is a tough problem, I know. It's not easy to clone things that are not 
cloneable, but at least 
ArrayList is!
```

Original issue reported on code.google.com by `snackbo...@googlemail.com` on 21 Sep 2009 at 8:40

**Comment by GoogleCodeExporter** [comment]
```
Yeah... Maybe we should do some special handling for cloneables... Let me think 
about
it...
```

Original comment by `szcze...@gmail.com` on 13 Oct 2009 at 8:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 20 Oct 2009 at 7:06
- Changed title: **Consider cloning parameters (or only collections) if they are clone'able to avoid mutable args problem**
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem here but my argument is not a collection.

My argument does not implement Cloneable but has a copy constructor instead.

```

Original comment by `cchaban...@gmail.com` on 4 Nov 2009 at 9:59

**Comment by GoogleCodeExporter** [comment]
```
With Easymock we don't have this problem :

IFoo mock = createMock(IFoo.class);
mock.foo(Arrays.asList("one"));
mock.foo(Arrays.<String> asList());
replay(mock);
List<String> list = new ArrayList<String>();
list.add("one");
mock.foo(list);
list.remove("one");
mock.foo(list);
verify(mock);

```

Original comment by `cchaban...@gmail.com` on 4 Nov 2009 at 10:44

**Comment by GoogleCodeExporter** [comment]
```
You're right, due to the record-playback pattern EM deals better with mutated
parameters. I probably have to put it somewhere in the limitations and EM vs 
Mockito
page.
```

Original comment by `szcze...@gmail.com` on 4 Nov 2009 at 1:12

**Comment by GoogleCodeExporter** [comment]
```
We should make sure there is no performance issue. Also, the implementation 
should be
safe (e.g. if deep clone throws, the exception should never reach the test)
```

Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 9:09
- Added labels: **Priority-Medium**
- Removed labels: **Priority-Low**

**Comment by GoogleCodeExporter** [comment]
```
starting to implement this with Szczepan.  we are using an answer to do this.  
examples 
and a check-in to look at soon.
```

Original comment by `wesandevie` on 18 Nov 2009 at 11:58
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
i am having an issue with the change.  it works fine when i run the tests from 
eclipse but the ant build is failing.

  <testcase classname="org.mockitousage.stubbing.CloningParameterTest" 
name="shouldVerifyEvenIfArgumentsWereMutated" time="0.047">
    <failure message="Classes must have the same type: class of the object from: 
class java.lang.Integer, mock super class: class java.lang.Number" 
type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError
: 
Classes must have the same type: class of the object from: class 
java.lang.Integer, 
mock super class: class java.lang.Number
    at 
org.mockito.internal.util.reflection.LenientCopyTool.copyToMock(LenientCopyTool.
java:
19)
    at org.mockito.stubbing.ClonesArguments.answer(ClonesArguments.java:15)
    at org.mockito.internal.MockHandler.handle(MockHandler.java:91)
    at 
org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodIntercepto
rFilt
er.java:47)
    at 
org.mockitousage.stubbing.CloningParameterTest$EmailSender$$EnhancerByMockitoWit
hCGLI
B$$cfbfb460.sendEmail(<generated>)
    at 
org.mockitousage.stubbing.CloningParameterTest.businessLogic(CloningParameterTes
t.jav
a:32)
    at 
org.mockitousage.stubbing.CloningParameterTest.shouldVerifyEvenIfArgumentsWereMu
tated
(CloningParameterTest.java:24)
</failure>

it seems to be having trouble deep cloning the int.  any idea why this would 
work in 
eclipse but not from ant?
```

Original comment by `wesandevie` on 18 Nov 2009 at 1:54

**Comment by GoogleCodeExporter** [comment]
```
strange, i have no idea how it passes in eclipse.  LenientCopyTool.copyToMock 
looks at 
the super class of the second parameter (new object to copy to) instead of the 
base 
class.  this probably makes since for a mock but not real classes.  looking at 
a fix 
now.
```

Original comment by `wesandevie` on 18 Nov 2009 at 2:10

**Comment by GoogleCodeExporter** [comment]
```
Deep cloning of an int? hmmmmm.... weird, it should be copied easily by value.
```

Original comment by `szcze...@gmail.com` on 20 Nov 2009 at 9:31

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 14 Feb 2010 at 10:03
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Issue 185 has been merged into this issue.
```

Original comment by `szcze...@gmail.com` on 24 May 2010 at 5:46

**Comment by GoogleCodeExporter** [comment]
```
Just encountered a need for this enhancement today. But I'm also leveraging the 
fact that mockito currently stores references to verify that the *same* 
references are being passed on each call to my mock.

Is there a way to have both references and cloning? Perhaps add 
ArgumentCaptor.getAllReferences() that returns references to method arguments 
and change ArgumentCaptor.getAllValues() to return the clones that were created 
at method-invocation time?

```

Original comment by `xedi...@gmail.com` on 16 Jun 2010 at 7:27

**Comment by GoogleCodeExporter** [comment]
```
We will definitely not change the current behavior. Clones idea is not fully 
implementable.
```

Original comment by `szcze...@gmail.com` on 21 Jun 2010 at 9:38

**Comment by GoogleCodeExporter** [comment]
```
Issue 234 has been merged into this issue.
```

Original comment by `szcze...@gmail.com` on 12 Dec 2010 at 10:14

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 12 Dec 2010 at 10:14

**Comment by GoogleCodeExporter** [comment]
```
Also had the need today to verify state that has been mutated. It would be 
great if there were an option to turn on cloning of parameters, e.g. when the 
mock is created.

It seems to be a common request, e.g. here: 
http://stackoverflow.com/questions/6613935/mockito-verify-state-halfway-through-
test

I would not want to switch back to EasyMock only for that. I really prefer 
Mockito because it is much more intutive, except for that little part, which is 
really counter-intuitive imho.

Here is my use / test case:


package test;

import static org.mockito.Matchers.argThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

import org.hamcrest.Description;
import org.junit.Test;
import org.junit.internal.matchers.TypeSafeMatcher;
import org.mockito.Mock;

import test.MockitoTest.App.Foo;
import test.MockitoTest.App.Notifier;

public class MockitoTest {

    static class App {
        static class Foo {
            private String state;
            public void setState(String state) {
                this.state = state;
            }
            public String getState() {
                return state;
            }
            @Override
            public String toString() {
                return "Foo in state: " + state;
            }
        }

        static interface Notifier {
            void stateChanged(Foo foo);
        }

        private final Notifier notifier;

        public App(final Notifier notifier) {
            this.notifier = notifier;
        }

        public void doStuff() {
            final Foo foo = new Foo();
            // ...do some stuff
            foo.setState("state 1");
            notifier.stateChanged(foo);
            // ...do more stuff
            foo.setState("state 2");
            notifier.stateChanged(foo);
        }
    }

    final Notifier notifier = mock(Notifier.class);
    final App app = new App(notifier);

    @Test
    public void testWeGetNotifiedAboutStateChangesOfFoo() throws Exception {
        app.doStuff();
        verify(notifier).stateChanged(fooWhereStateIs("state 1")); // => fails here
        verify(notifier).stateChanged(fooWhereStateIs("state 2"));
    }

    private Foo fooWhereStateIs(final String expectedState) {
        return argThat(new TypeSafeMatcher<Foo>() {
            public void describeTo(Description description) {
                description.appendText("Foo in state: ").appendValue(expectedState);
            }
            @Override
            public boolean matchesSafely(Foo actual) {
                return actual.getState().equals(expectedState);
            }
        });
    }
}


```

Original comment by `deru...@gmail.com` on 14 Mar 2012 at 6:17

**Comment by GoogleCodeExporter** [comment]
```
Well, I have just tried this: 

mock(Notifier.class, withSettings().defaultAnswer(new ClonesArguments()));

It works for the test case above, but not sure whether it works in our real 
world code as well... (have to give it a try tomorroy) 

Can you give an example for the cases where it does not work? 

Cheers,
Torben
```

Original comment by `deru...@gmail.com` on 14 Mar 2012 at 6:23

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Here's what I would say :
- This answer has not been fully tested with different configuration.
- It doesn't do deepClones.
- It probably won't work if you are using stubs, as the default answer 
CloneArguments will be replaced by the one of the stub.
- The code won't work if the argument is a primitive type.
- This class is internal so it might change from version to version, maybe even 
removed.

In the end you will be safer if you create your own CloneAnswer in your test 
code base.

Hope that helps,
Brice
```

Original comment by `brice.du...@gmail.com` on 15 Mar 2012 at 11:39
