### ISSUE TITLE
occasional ArrayIndexOutOfBoundsException when calculating stack traces for reporting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#134]
```
What steps will reproduce the problem?
1. I'm really not sure how to reproduce this, except to say that it is
happening for me in rare circumstances.

What is the expected output? What do you see instead?

Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at org.mockito.internal.debugging.Location.<init>(Location.java:16)
    at org.mockito.internal.invocation.Invocation.<init>(Invocation.java:55)
    at
org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodIntercepto
rFilter.java:49)
    at
com.....MyClass$$EnhancerByMockitoWithCGLIB$$851c5a34.someMethod(<generated>)

What version of the product are you using? On what operating system?

1.8, XP.

Please provide any additional information below.

The object that triggers the exception when I invoke a method is spied on.


```

Original issue reported on code.google.com by `jhalter...@gmail.com` on 27 Oct 2009 at 8:19

**Comment by GoogleCodeExporter** [comment]
```
I fixed it in trunk. Location is only for making the exception messages extra 
nice
and should never break in case there is something wrong with the stack traces.
```

Original comment by `szcze...@gmail.com` on 28 Oct 2009 at 8:11
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks!
```

Original comment by `jhalter...@gmail.com` on 28 Oct 2009 at 8:25

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 1:33
- Added labels: **Milestone-Release1.8.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 2:41
- Changed title: **occasional ArrayIndexOutOfBoundsException when calculating stack traces for reporting**
