### ISSUE TITLE
Arrays should be matched for equals() using their content

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#141]
```
Hi there,

we are using the new ArgumentCaptor to verify method call arguments.
In our case its specially the JPA EntityManager#persist() method wichs
arguments we would like to verify. In our test it is called three times
with different entity classes and we have setup our verifications to track
this.
But after the first veryify statement this exception is thrown:

org.mockito.exceptions.verification.TooManyActualInvocations: 
entityManager.persist(<Capturing argument>);
Wanted 1 time:
-> at
de.llynch.endion.asp.integration.esb.LinkTrackingProcessorTest.testLinkTracking(
LinkTrackingProcessorTest.java:103)
But was 3 times. Undesired invocation:
-> at
de.llynch.endion.asp.integration.esb.LinkTrackingProcessor.updateProfile(LinkTra
ckingProcessor.java:129)

        at
de.llynch.endion.asp.integration.esb.LinkTrackingProcessorTest.testLinkTracking(
LinkTrackingProcessorTest.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at
org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java
:44)
        at
org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:
15)

```

Original issue reported on code.google.com by `knista.peter` on 9 Nov 2009 at 8:07

**Comment by GoogleCodeExporter** [comment]
```
Then please use atLeastOnce() with verification.
```

Original comment by `szcze...@gmail.com` on 9 Nov 2009 at 8:54

**Comment by GoogleCodeExporter** [comment]
```
I already do use atLeastOnce() and it does not work.
```

Original comment by `knista.peter` on 10 Nov 2009 at 8:17

**Comment by GoogleCodeExporter** [comment]
```
Hmmmm, I'm not sure what's up. The stack trace you submitted tells me that you 
do:

verify(entityManager).persist(<Capturing argument>);

By default, verify checks for single invocation of the method. Therefore this 
should
work:

verify(entityManager, atLeastOnce()).persist(<Capturing argument>);

Are you sure you get the very same exception when you use atLeastOnce() ?

Also, can you reduce the test and submit a test case that reproduces the 
incorrect
behavior?

Thanks!
```

Original comment by `szcze...@gmail.com` on 10 Nov 2009 at 9:43

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r1679.
```

Original comment by `szcze...@gmail.com` on 10 Nov 2009 at 10:10
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Sorry, it wasn't fixed by any revision. Messed up svn comment.
```

Original comment by `szcze...@gmail.com` on 10 Nov 2009 at 10:39
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision a91a2196c4.
```

Original comment by `szcze...@gmail.com` on 7 Oct 2010 at 5:21
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 3 Jul 2011 at 12:43
- Added labels: **Milestone-Release1.9-rc1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 16 Jul 2011 at 8:57
- Changed title: **Arrays should be matched for equals() using their content**
