### ISSUE TITLE
internal process tweak for verifiction with matchers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#144]
```
What steps will reproduce the problem?
1. I create a custom ArgumentMatcher.
2. I call my readUser method
3. I call my saveUser method
4. verify(userManager).readUser(any(UUID.class));
5. verify(userManager).saveUser((UserDetail)argThat(new MyArgumentMatcher()))
6. MyArgumentMatcher.matches() is called to verify argument in saveUser,
but it is called to verify argument in readUser too.

What is the expected output? What do you see instead?
MyArgumentMatcher only should be called to check argument in saveUser
method. It should NOT called to check argument in readUser method.

What version of the product are you using? On what operating system?
1.7 and 1.8.0

Please provide any additional information below.

MyArgumentMatcher is called by InvocationMatcher's hasSimilarMethod:

    public boolean hasSimilarMethod(Invocation candidate) {
        String wantedMethodName = getMethod().getName();
        String currentMethodName = candidate.getMethod().getName();

        final boolean methodNameEquals =
wantedMethodName.equals(currentMethodName);
        final boolean isUnverified = !candidate.isVerified();
        final boolean mockIsTheSame = getInvocation().getMock() ==
candidate.getMock();
        final boolean methodEquals = hasSameMethod(candidate);
        final boolean overloadedButSameArgs = !methodEquals &&
safelyArgumentsMatch(candidate.getArguments());        

        if (methodNameEquals && isUnverified && mockIsTheSame &&
!overloadedButSameArgs) {
            return true;
        }

        return false;
    }

When it checks readUser method, methodNameEquals is false, but to assign
overloadedButSameArgs variable, it call safelyArgumentsMatch(...), that it
call MyArgumentMatcher. I think if methodNameEquals is false should not
call safelyArgumentsMatch.
```

Original issue reported on code.google.com by `alex.gue...@gmail.com` on 11 Nov 2009 at 9:58

**Comment by GoogleCodeExporter** [comment]
```
Sounds good, we can change it. Does the fact that matcher is called multiple 
times
makes your test misbehave?
```

Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 11:09

**Comment by GoogleCodeExporter** [comment]
```
If matcher is called to check saveUser, no problem. But if matcher is called to 
check
readUser, argument that it receives is an UUID instead of UserDetail (see 
points #4 &
#5). Matcher expects receive an UserDetail argument and if it doesn't receive 
it a
ClassCastException is thrown. If I check argument class and return false in 
case of
argument is not UserDetail instance, verify result is wrong.
```

Original comment by `alex.gue...@gmail.com` on 11 Nov 2009 at 11:40

**Comment by GoogleCodeExporter** [comment]
```
>Matcher expects receive an UserDetail argument and if it doesn't receive it a
ClassCastException is thrown

That's correct but the client does not see this exception because of 
'safelyMatch',
right?
```

Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 12:43

**Comment by GoogleCodeExporter** [comment]
```
Another issue related with this. Because of call argument matcher for methods, 
even
if method name does NOT matches, method captureArgumentsFrom in 
InvocationMatcher
fails when there is a method without arguments in mock:

    public void captureArgumentsFrom(Invocation i) {
        int k = 0;
        for (Matcher m : matchers) {
            if (m instanceof CapturesArguments) {
                ((CapturesArguments) m).captureFrom(i.getArguments()[k]);
            }
            k++;
        }
    }

if i.getArguments() returns a emtpy array, i.getArguments()[k] throw an
ArrayIndexOutOfBoundsException:

ava.lang.ArrayIndexOutOfBoundsException: 0
    at
org.mockito.internal.invocation.InvocationMatcher.captureArgumentsFrom(Invocatio
nMatcher.java:116)
    at
org.mockito.internal.invocation.InvocationMarker.markVerified(InvocationMarker.j
ava:14)
    at
org.mockito.internal.verification.checkers.AtLeastXNumberOfInvocationsChecker.ch
eck(AtLeastXNumberOfInvocationsChecker.java:31)
    at org.mockito.internal.verification.AtLeast.verify(AtLeast.java:38)
    at org.mockito.internal.MockHandler.handle(MockHandler.java:75)
    at
org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodIntercepto
rFilter.java:50)
    at
com.isotrol.merlin3.CategoryManager$$EnhancerByMockitoWithCGLIB$$87d525e6.readCh
ildren(<generated>)
    at
com.isotrol.merlin3.server.operationProcessors.category.CategoryListRelatedConte
ntTest.getCategoriesNewsWithEmptyId(CategoryListRelatedContentTest.java:303)
    at
com.isotrol.merlin3.server.operationProcessors.category.CategoryListRelatedConte
ntTest.testGetCategoriesWithEmptyId(CategoryListRelatedContentTest.java:128)


Thanks a lot for your attention, I hope my modest contribution helps you. 
```

Original comment by `alex.gue...@gmail.com` on 11 Nov 2009 at 12:45

**Comment by GoogleCodeExporter** [comment]
```
>That's correct but the client does not see this exception because of 
'safelyMatch',
right?
Right, I got an error in JUnit test, but maybe it was 1.7 version. I changed to 
1.8.0
and I got a new error, but maybe it was a real error in my code. Anyway, I will 
use
ArgumentCaptor (new in 1.8.0) to check my code. I think that in my case is 
clearer. 

In other hand, I think comment #4 it is an error in mockito. 

Thanks.
```

Original comment by `alex.gue...@gmail.com` on 11 Nov 2009 at 1:05

**Comment by GoogleCodeExporter** [comment]
```
>ArrayIndexOutOfBoundsException

Yup, we've got it fixed in trunk. The release is on the way =)
```

Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 1:05

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r1691.
```

Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 1:07
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks a lot.;-)
```

Original comment by `alex.gue...@gmail.com` on 11 Nov 2009 at 1:13

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 1:33
- Added labels: **Milestone-Release1.8.1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 11 Nov 2009 at 2:40
- Changed title: **internal process tweak for verifiction with matchers**

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 2 Dec 2012 at 10:21
- Added labels: **Matchers**
