### ISSUE TITLE
Print all recorded interactions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#148]
```
This is an enhancement suggestion.

When debugging a test failure, it's often very useful to look at what
interactions are actually happening - it'd be great to be able to do
something like:

Mockito.dumpInteractions(mock1, mock2, mock3);

and have it give a time-sorted list of interactions for the given objects.
It could include the method calls, its parameters, return value, and if the
call was stubbed, where exactly the stub was defined (short stack trace).
```

Original issue reported on code.google.com by `rdamazio@gmail.com` on 13 Nov 2009 at 10:18

**Comment by GoogleCodeExporter** [comment]
```
Interesting request. Also, you can play a little bit with 
VerboseMockitoJUnitRunner
and give me some feedback.
```

Original comment by `szcze...@gmail.com` on 13 Nov 2009 at 10:36

**Comment by GoogleCodeExporter** [comment]
```
Actually, I'm using Mockito in Android tests, so I can't replace the JUnit 
runner.
```

Original comment by `rdamazio@gmail.com` on 13 Nov 2009 at 10:39

**Comment by GoogleCodeExporter** [comment]
```
I added some new stuff to trunk:

Mockito.debug().printInvocations(mocks);

Have a play with it. However, I'm not sure if it makes its way to the release 
in this
particular form. I'm kind of thinking that I should focus on unused stubs / 
stubs
called with wrong parameters.
```

Original comment by `szcze...@gmail.com` on 15 Nov 2009 at 8:27

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 14 Feb 2010 at 9:50
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
I was looking for exactly this feature and for exactly the same reasons as 
rdamazio
illustrated.

However, instead of embedding the printing logic inside of Mockito itself, 
could you
allow the printing/logging to be implemented in terms of a more general callback
facility so that I have full control over what is printed?

It would look something like:

public interface InvocationCallback {
    void preInvocation(InvocationOnMock invocation);
}

public class LoggingCallback implements InvocationCallback {
   public void preInvocation(InvocationOnMock invocation) {
      System.out.println( "about to invoke " + invocation );
   }
}

Foo mock = mock( Foo.class, withSettings().callback( new LoggingCallback() ) );

With this approach the printing is controllable on a per-mock basis, is 
localized to
the mock creation site, and does not require any particular test runner.

Thoughts?
```

Original comment by `brian.la...@gmail.com` on 20 May 2010 at 7:15

**Comment by GoogleCodeExporter** [comment]
```
The idea sounds good, but I'd still like to have a default/built-in printing 
mechanism so I don't have it bother 
writing it if I don't want to.
```

Original comment by `rdamazio@gmail.com` on 20 May 2010 at 8:22

**Comment by GoogleCodeExporter** [comment]
```
Perhaps something like:

withSettings().verbose()

as an alias for

withSettings().callback( new DefaultMockitoLoggingCallback() )

Or, if you wanted to make this feature consistent with the other mock(Class, 
setting)
methods, perhaps introduce some kind of Verbosity/Printing enum so you end up 
with:

withSettings().logging( Logging.VERBOSE )

as an alias for

withSetting().callback( new VerboseLoggingCallback() )

so that you also get

Mockito.mock(Class<T> class, Logging verbosity)

The enum could be a simpler boolean instead if no one can think of useful enum
settings other than, say, Logging.VERBOSE and Logging.SILENT.
```

Original comment by `brian.la...@gmail.com` on 20 May 2010 at 10:33

**Comment by GoogleCodeExporter** [comment]
```
This is really cool idea. Do you want to take a stab at implementation? I very 
much
like the fact that we don't have to extend the public api :D
```

Original comment by `szcze...@gmail.com` on 22 May 2010 at 11:46

**Comment by GoogleCodeExporter** [comment]
```
Sure, I'll try coming up with a patch. Unfortunately, my free time is premium 
for the
near future so it may be a while before I can dedicate enough time to yield 
quality
implementation. I'll keep you posted.
```

Original comment by `brian.la...@gmail.com` on 25 May 2010 at 8:12

**Comment by GoogleCodeExporter** [comment]
```
This sounds great.  

Brian - if I understand correctly, your callback idea would allow "real-time" 
tracing of invocations (and stubbing?) as they happen, rather than the "log 
everything internally and then dump it all out at the end" approach suggested 
by the original reporter?  

Real-time sounds more useful, although I agree with comment 6 that ideally 
there should be a default callback handler so API consumers can enable basic 
tracing without having to add more than a single line of code.
```

Original comment by `adam.spi...@gmail.com` on 7 Sep 2010 at 10:02

**Comment by GoogleCodeExporter** [comment]
```
I'd like to work on a patch for this issue.

API wise, I'd go with Brian's verbose() + callback(Callback) Variant. I don't 
think it necessary to provide the SILENT level. It is the default anyways, and 
its only one more argument one needs to know when enabling debug mode.

Implementation wise, I'd extend MockSettingsImpl, obviously. Then, if I 
understand correctly, MockHandler needs to call the callback handler. Though it 
could (try to) ignore invocations during stubbing / verification, I'd simply 
log everything. If logging is truly to be activated for each mock individually, 
there isn't much spamming anyways.

Is this feature still requested? Do you agree in principle with this 
implementation proposal? Hints, Recommendations, etc. welcome. Otherwise, I'd 
start working on it.

Regards,
Murat
```

Original comment by `murat.kn...@googlemail.com` on 13 Feb 2011 at 8:20

**Comment by GoogleCodeExporter** [comment]
```
Hi Murat,

I agree with the brian suggestions, however instead of logging I would rather 
see  verboseLogging, it's more expressive on the intent than just verbose.

Anyway you got the idea on how to implement the stuff.

Regards,
Brice

```

Original comment by `brice.du...@gmail.com` on 13 Feb 2011 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
Okay, I'll give it a try, then.
```

Original comment by `murat.kn...@googlemail.com` on 13 Feb 2011 at 9:06

**Comment by GoogleCodeExporter** [comment]
```
cool. withSettings().verboseLogging() makes sense to me.
```

Original comment by `szcze...@gmail.com` on 15 Feb 2011 at 9:59

**Comment by GoogleCodeExporter** [comment]
```
Currently I have an implementation based on the public InvocationOnMock 
interface. With it, I can provide only limited information to the listeners and 
can only log which method was called and its arguments. Any more information 
would have to include internal objects, such as Invocation.

Since I assume that the contents of the internal package are subject to change 
at any moment, including any of them in the "public" listener interface could 
mean subtle or even API changes for users. Then again, the listeners should be 
short-lived anyways, and used for debugging only. Therefore, I'd favor the 
unstable, yet more useful solution.

I'd appreciate your input on this — doesn't help me favoring anything, if you 
decide not to accept it. ;)

```

Original comment by `murat.kn...@googlemail.com` on 17 Feb 2011 at 6:45

**Comment by GoogleCodeExporter** [comment]
```
Hi, I'm not sure to follow your reasoning there.

InvocationOnMock allows access to arguments, method and mock. Why would you 
need access to the implementation?

However I must say I'd rather not expose InvocationOnMock.callRealMethod in the 
callback mecanism. You might instead want to enrich the existing 
PrintableInvocation interface.


Anyway I would clearly not expose internals this way.
```

Original comment by `brice.du...@gmail.com` on 17 Feb 2011 at 7:54

**Comment by GoogleCodeExporter** [comment]
```
Following the requested features from post 1, I was not sure how to get the 
stack trace (Location) and stub definition (StubInfo/PrintableInvocation) 
without relying on internals.

PrintableInvocation itself is internal already, including the location, which 
one of its methods returns, which is why I didn't consider it in the first 
place.

Nevertheless, if you favor this interface, then I don't see where we disagree. 
(Which is good ;)
Extension of the interface is not necessary, I think, since the other required 
infos (return value, stubbing info) are not included in the Invocation object 
anyways.

And true, callRealMethod is not something an invocation listener needs to have 
— and therefore shouldn't have.

Continuing with PrintableInvocation (unless someone objects) ...
```

Original comment by `murat.kn...@googlemail.com` on 17 Feb 2011 at 8:20

**Comment by GoogleCodeExporter** [comment]
```
Ok I see your point, Location indeed is located in internal package, maybe we 
might change this.

You can also create another object with an interface, like 
LoggableInvocationInformation, or whatever making sense. Taking an Invocation, 
and exposing public objects of this Invocation. You might want to investigate 
InvocationMatcher, it holds a few interesting things.
```

Original comment by `brice.du...@gmail.com` on 17 Feb 2011 at 11:09

**Comment by GoogleCodeExporter** [comment]
```
Hi, I've prepared a patch at the following branch. I'd appreciate feedback on 
anything that needs change.

http://code.google.com/r/muratknecht-mockito-issue148/

The API is as agreed:

Foo foo = mock(Foo.class, withSettings().verboseLogging());

and

Foo foo = mock(Foo.class, withSettings().callback(new RememberingListener()));

The former will print invocation infos to std out. Here an example. This is 
just a proposal, of course. The location info (-> at ...), however, is simply 
what the listener gets, and therefor cannot be changed without exposing 
Location and its fields.


############ Logging method invocation #3 on mock/spy ########
foo.giveMeSomeString("another string value");
   -> at org.mockitousage.debugging.VerboseLoggingOfInvocationsOnMockTest.usage(VerboseLoggingOfInvocationsOnMockTest.java:154)
   Will return: >some return value< (java.lang.String)
   Method has been stubbed.
   -> at org.mockitousage.debugging.VerboseLoggingOfInvocationsOnMockTest.usage(VerboseLoggingOfInvocationsOnMockTest.java:149)
###########################################################


The usage-level tests are InvocationListenerCallbackTest and 
VerboseLoggingOfInvocationsOnMockTest. You may want to have a closer look at 
the latter (see the class comment). As always with usage-level tests that make 
assertions regarding the contents of the standard output stream, it gets a bit 
messy.
```

Original comment by `murat.kn...@googlemail.com` on 23 Feb 2011 at 10:46

**Comment by GoogleCodeExporter** [comment]
```
Hi Murat,

Commit the patch to your repo ;)
https://code.google.com/r/muratknecht-mockito-issue148/source/list doesn't 
contain your modifications.

However I don't like the RememberingListener name, I'm not sure about how to 
name it, looking at the API of this object might help to refine the concept of 
this listener.

Regards,
Brice
```

Original comment by `brice.du...@gmail.com` on 26 Feb 2011 at 10:29

**Comment by GoogleCodeExporter** [comment]
```
sorry, thought I pushed my changes. now done.

any proposals welcome. :)
```

Original comment by `murat.kn...@googlemail.com` on 26 Feb 2011 at 4:06

**Comment by GoogleCodeExporter** [comment]
```
Hi,

just wanted to check on the status of the patch. Did you have time to look at 
the code yet?

regards,
murat
```

Original comment by `murat.kn...@googlemail.com` on 5 Mar 2011 at 10:36

**Comment by GoogleCodeExporter** [comment]
```
Got busy last week, anyway I just took a look at your patch. There is a few 
small issues like naming, callback should accept vararg, some tests seems a bit 
like overkill, etc. However the essential stuff is there, corner cases seem to 
be addressed, right now I'm focusing on another area of mockito, so don't worry 
if I don't integrate your work immediately.
Thanks for your work :)

Brice
```

Original comment by `brice.du...@gmail.com` on 8 Mar 2011 at 1:07

**Comment by GoogleCodeExporter** [comment]
```
Okay, no hurry. Just thought, if there were questions, I would now be better 
able to answer them than later. ;)

Moving on ...

Regards,
Murat
```

Original comment by `murat.kn...@googlemail.com` on 8 Mar 2011 at 8:38

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 9 May 2011 at 8:45

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 5 Jul 2011 at 7:36
- Changed state: **Fixed**
- Added labels: **Milestone-Release1.9-rc1**
