### ISSUE TITLE
Mockito as OSGi bundle: Failed, missing package(s) or can not resolve all of the them

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#158]
```
What steps will reproduce the problem?
1. Write an OSGi integration test using the Spring DM testing framework
inheriting from
org.springframework.osgi.test.AbstractConfigurableBundleCreatorTests, and
calling Mockito's "verify(...)" method somewhere
2. Attempt to run it as a JUnit test in Eclipse 3.5

The error I get using the Spring DM integration testing framework is:

 java.lang.IllegalStateException: Unable to dynamically start generated
unit test bundle
    at
org.springframework.osgi.test.AbstractOnTheFlyBundleCreatorTests.postProcessBund
leContext(AbstractOnTheFlyBundleCreatorTests.java:527)
    at
org.springframework.osgi.test.AbstractConfigurableBundleCreatorTests.postProcess
BundleContext(AbstractConfigurableBundleCreatorTests.java:223)
    at
org.springframework.osgi.test.AbstractOsgiTests.startup(AbstractOsgiTests.java:2
62)
    at
org.springframework.osgi.test.AbstractOsgiTests.prepareTestExecution(AbstractOsg
iTests.java:374)
    at
org.springframework.osgi.test.AbstractOsgiTests.runBare(AbstractOsgiTests.java:2
03)
    at
org.springframework.osgi.test.AbstractOsgiTests$1.protect(AbstractOsgiTests.java
:184)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at
org.springframework.osgi.test.AbstractOsgiTests.run(AbstractOsgiTests.java:181)
    at junit.framework.TestSuite.runTest(TestSuite.java:230)
    at junit.framework.TestSuite.run(TestSuite.java:225)
    at
org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestR
eference.java:130)
    at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:467)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:683)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:390)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:197)
Caused by: org.osgi.framework.BundleException: Failed, missing package(s)
or can not resolve all of the them: org.mockito.internal.verification.api
    at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:313)
    at
org.springframework.osgi.test.AbstractOnTheFlyBundleCreatorTests.installAndStart
Bundle(AbstractOnTheFlyBundleCreatorTests.java:547)
    at
org.springframework.osgi.test.AbstractOnTheFlyBundleCreatorTests.postProcessBund
leContext(AbstractOnTheFlyBundleCreatorTests.java:524)
    ... 15 more


In fact, I cannot use any of the verification facilities of Mockito inside
the OSGi container of the Spring DM testing framework. The code that won't
work for me is:

 MessageListener listener = mock(MessageListener.class);
 verify(listener2,times(1)).onMessage(any(Message.class));

First line is ok, but the second causes the class loading issue. If I
comment it out, everything works as expected.

In the mockito manifest file I can't locate the import statement for the
org.mockito.internal.verification.api package. Why not use an entry like

 Bundle-Classpath: .

to let the bundle be resolved? Or will this mess up the existing manifest?


```

Original issue reported on code.google.com by `zla...@gmail.com` on 14 Dec 2009 at 12:32

**Comment by GoogleCodeExporter** [comment]
```
Ok, sorry. I just realized that my suggestion won't solve the problem.
See http://www.osgi.org/download/r4v42/r4.core.pdf, Chapter 3.8.1 
("Bundle-Classpath:
." is the default).

I'll have to investigate a bit more. Might not be a Mockito issue after all. 

Can this issue be deleted?
```

Original comment by `zla...@gmail.com` on 14 Dec 2009 at 12:37

**Comment by GoogleCodeExporter** [comment]
```
Don't worry - leave this issue open. If you find out what's up and it's Mockito 
fault
then please help us improve Mockito osgi bundle. I'm not OSGi expert :)
```

Original comment by `szcze...@gmail.com` on 14 Dec 2009 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
quick and dirty solution:
add ",org.mockito.internal.verification.api" to the export statement
in the manifest
```

Original comment by `oliver.k...@googlemail.com` on 13 Jan 2010 at 1:46

**Comment by GoogleCodeExporter** [comment]
```
Thanks oliver, that fixed my problem.

Will the org.mockito.internal.verification.api package at some point become
"external"? Or at least classes that are used in the main API (i.e.
org.mockito.Mockito class), just as the VerificationMode class? From an OSGi 
point of
view, i think such classes definitely need to be in an package which is 
exported by
the Mockito bundle.
```

Original comment by `zla...@gmail.com` on 10 Feb 2010 at 5:47

**Comment by GoogleCodeExporter** [comment]
```
ah.... It's a mistake and it should be public.
```

Original comment by `szcze...@gmail.com` on 11 Feb 2010 at 8:07

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r1852.
```

Original comment by `szcze...@gmail.com` on 14 Feb 2010 at 9:47
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Cool! Looking forward to the next release. Mockito rules! 
```

Original comment by `zla...@gmail.com` on 15 Feb 2010 at 5:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 28 Feb 2010 at 9:04
- Added labels: **Milestone-Release1.8.3**
