### ISSUE TITLE
@Mock fields in super test class are not injected on @InjectMocks fields

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#229]
```
What steps will reproduce the problem?
1. Consider there are 2 Junit 4 tests, one is BaseTest and the other is 
ImplicitTest like bellow:
   @Ignore
   public abstract class BaseTest {
     @Mock
     protected DaoA dao;

   }


   public class ImplicitTest extends BaseTest {
     @InjectMocks
     private SystemUnderTest sut = new SystemUnderTest();

     @Before
     public void setup() {
       MockitoAnnotations.initMocks(this);
     }

     @Test
     public void test1() {
        sut.businessMethodA();
     }     
   }

   public class SystemUnderTest {
     private DaoA dao;
     public void setDao(DaoA dao) {
       this.dao = dao;
     }

     public void businessMethodA() {
        dao.doQuery();
     }
   }


   public class DaoA {
     public void doQuery(){
     }
   }
2. when I run "test1()" method, a NullPointException will throw out as bellow:
   java.lang.NullPointerException
    at SystemUnderTest.businessMethodA(SystemUnderTest.java:9)
    at ImplicitTest.test1(ImplicitTest.java:17)

3. when I add one more line code in "test1()" then the case can pass, the 
"test1()" method when the case pass is :
    @Test
    public void test1() {
        sut.setDao(dao);
        sut.businessMethodA();
    }


What is the expected output? What do you see instead?
expected: I can inject the mock object defined by @Mock in super class
actual :  The mock object defined by @Mock annotation in super class can NOT 
inject into the SUT defined in child class.

What version of the product are you using? On what operating system?
Mockito Version: mockito-all-1.8.5.jar
Operation System: windows vista
java -version :
java version "1.6.0_20"
Java(TM) SE Runtime Environment (build 1.6.0_20-b02)
Java HotSpot(TM) Client VM (build 16.3-b01, mixed mode, sharing)

Please provide any additional information below.


```

Original issue reported on code.google.com by `ace...@gmail.com` on 1 Nov 2010 at 11:02

**Comment by GoogleCodeExporter** [comment]
```
Perfect bug report! I reproduced it in a matter of seconds.
I will look into it!
```

Original comment by `brice.du...@gmail.com` on 3 Nov 2010 at 1:48
- Changed title: **@Mock fields in super test class are not injected on @InjectMocks fields**

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 7 Nov 2010 at 5:54
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 16 Dec 2010 at 3:37
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 3 Jul 2011 at 12:43
- Added labels: **Milestone-Release1.9-rc1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 3 Sep 2012 at 10:00
- Added labels: **Injection**

**Comment by GoogleCodeExporter** [comment]
```
Hello I am using mockito 1.9 and I seem to be having this exact issue.

public abstract class AbstractClass {
@Autowired(required=true) Dependency dependency;
protected void protectedMethod(){dependency.doSomething();}
}

@Service
public class ImplClass extends AbstractClass {
public void methodIWantToTest(){ protectedMethod();}
}

@RunWith(PowerMockRunner.class)
public class ImplClassTest(){
    @InjectMocks
    ImplClass service;
    @Mock
    Dependency dependency;
@Test 
public void testMethodIwantToTest(){
  service.methodIWantToTest();
}
}
I am getting a NullPointerException on dependency.doSomething because 
dependency does not get mocked.
```

Original comment by `mmarti...@oreillyauto.com` on 28 Jan 2013 at 6:01

**Comment by GoogleCodeExporter** [comment]
```
Hi the sample you showed me uses PowerMockRunner which is not part of this 
project, maybe that's the issue.
```

Original comment by `brice.du...@gmail.com` on 28 Jan 2013 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
i had similar issue true @mock not injects if its a super class one so for your 
@injectMocks object super class add a setter and set mock in u r test case it 
will work 

SystemUnderTest.setDao()
```

Original comment by `uday1312...@gmail.com` on 10 Oct 2014 at 2:32
