### ISSUE TITLE
NullPointerException in Mockito#verify() with same()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#231]
```
When using Mockio#verify() like below
  verify( object ).method( same( null ) );
... a NullPointerException occurs if the verification fails. The exception 
arises while describing why verify failed.


java.lang.NullPointerException
    at org.mockito.internal.matchers.Same.describeTo(Same.java:29)
    at org.mockito.internal.matchers.LocalizedMatcher.describeTo(LocalizedMatcher.java:33)
    at org.hamcrest.BaseDescription.appendDescriptionOf(BaseDescription.java:21)
    at org.hamcrest.BaseDescription.appendList(BaseDescription.java:78)
    at org.hamcrest.BaseDescription.appendList(BaseDescription.java:69)
    at org.mockito.internal.matchers.MatchersPrinter.getArgumentsLine(MatchersPrinter.java:21)
    at org.mockito.internal.invocation.Invocation.toString(Invocation.java:130)
    at org.mockito.internal.invocation.InvocationMatcher.toString(InvocationMatcher.java:53)
    at org.mockito.exceptions.Reporter.createWantedButNotInvokedMessage(Reporter.java:261)
    at org.mockito.exceptions.Reporter.wantedButNotInvoked(Reporter.java:256)
    at org.mockito.internal.verification.checkers.MissingInvocationChecker.check(MissingInvocationChecker.java:41)
    at org.mockito.internal.verification.Times.verify(Times.java:35)
    at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:22)
    at org.mockito.internal.MockHandler.handle(MockHandler.java:79)
    at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:47)

```

Original issue reported on code.google.com by `ruediger...@gmx.de` on 17 Nov 2010 at 3:36

**Comment by GoogleCodeExporter** [comment]
```
Ok, this is a bug, the NPE shouldn't be raised here.

Since the value is null, you should use instead org.mockito.Matchers.eq(Object) 
which is protected against null values.

The same matcher seems misappropriated here, same stands for "same instance". 
The null value is not an instance. I would rather go for isNull or eq(null) 
matchers.
```

Original comment by `brice.du...@gmail.com` on 18 Nov 2010 at 4:27
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 18 Nov 2010 at 4:56
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 3 Jul 2011 at 12:43
- Added labels: **Milestone-Release1.9-rc1**

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 2 Dec 2012 at 10:21
- Added labels: **Matchers**
