### ISSUE TITLE
InOrder.verify() displays the actual invocation on error when arguments are different

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#27]
```
Mocking Outputstream to verify we write first a single byte, followed by an 
array of bytes.

Intentionally 'breaking' the tests by verifying the single byte as the 
incorrect character.

When we use inOrder to verify and have an incorrect value set, the actual 
invocation is not shown.  Without inOrder, does show.

With inOrder:

org.mockito.exceptions.verification.WantedButNotInvoked: 
Wanted but not invoked:
outputStream.write(3);
    at WriterTest.testWriteInOrder(WriterTest.java:29)

Without inOrder:

org.mockito.exceptions.verification.ArgumentsAreDifferent: 
Argument(s) are different! Wanted:
outputStream.write(3);
    at WriterTest.testWrite(WriterTest.java:36)
Caused by: org.mockito.exceptions.cause.ActualArgumentsAreDifferent: 
Actual invocation has different arguments:
outputStream.write(4);
    at WriterTest.write(WriterTest.java:16)
    at WriterTest.testWrite(WriterTest.java:35)



```

Original issue reported on code.google.com by `nathan.m...@gmail.com` on 13 Oct 2008 at 8:31

Attachments:
- [WriterTest.java](https://storage.googleapis.com/google-code-attachments/mockito/issue-27/comment-0/WriterTest.java)

**Comment by GoogleCodeExporter** [comment]
```
Using Java 6, Junit 4 and mockito-all-1.5.jar
```

Original comment by `nathan.m...@gmail.com` on 13 Oct 2008 at 8:32

**Comment by GoogleCodeExporter** [comment]
```
Well spotted. 

This one is just not implemented. At the time when I implemented inOrder it was
somewhat difficult to get actual invocation working in the way it works without
inOrder. It's just few times one really needs inOrder so it never had high 
prority. I
will look how easy is to get working as you suggest.

You surely know how to use Mockito :) Did you find this bug when doing actual 
coding
or when testing mockito in anger?
```

Original comment by `szcze...@gmail.com` on 13 Oct 2008 at 4:35

**Comment by GoogleCodeExporter** [comment]
```
Actual code.  Having to write tests for some legacy code before we attempt to
refactor it.  Means we're stuck writing tests for some pretty awful code, so 
being
able to use in order for OutputStream writes is important.
```

Original comment by `nathan.m...@gmail.com` on 13 Oct 2008 at 8:50

**Comment by GoogleCodeExporter** [comment]
```
Ok, thanks.

InOrder should work correctly it's just it doesn't have such nice error 
reporting as
ordinary verification.

I know it's legacy code but I would strive to test OutputStream without mocks. 
Using
OS is more less like building a state so ideally I would assert on that state. 
If you
write out text then it's fairly easy to assert on the content. If it's binary 
then
it's harder. Still you might eventually end up with a thin layer around OS. This
means that the verification on OS becomes quite obsolete.

Last hint that comes to me is that you could start up by writing ordinary
verification. Then, when all the interactions and arguments match (green bar:) 
you
might change verify to inOrder.verify
```

Original comment by `szcze...@gmail.com` on 14 Oct 2008 at 9:44

**Comment by GoogleCodeExporter** [comment]
```
Yeah, I agree OutputStream isn't a great thing to check with mocks.  But it's 
what I 
was using at the time so made for a simple use case for the issue.

I think one of the (many) good things about mockito is that if you do insist on 
doing 
something the 'bad' way, it lets you do it without penalizing you for not 
knowing how 
to write a good test at the time.  If gives you the chance to see for yourself 
there's a better way to do testing.

With OutputStream we originally wanted to ensure that writers were called in a 
certain order and that no other methods (such as flush or close) were called.  
Looking at our tests now though, can see that every test just relies on the 
write 
methods, so will probably roll our own extension of ByteArrayOutputStream that 
throws 
exceptions on all but the write methods.  We can then examine the contents on 
the 
resulting array to confirm the bytes we expected were written.

We did end up using your hint, to remove the inOrder (which is where i hit 
issue 28 
hehe) and then add it back in once the green bar appears.  Worked for us, but 
obviously not ideal for a long lived test class.
```

Original comment by `nathan.m...@gmail.com` on 15 Oct 2008 at 12:37

**Comment by GoogleCodeExporter** [comment]
```
I'll try to fix it in the next version.
```

Original comment by `szcze...@gmail.com` on 21 Oct 2008 at 2:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 21 Oct 2008 at 2:40
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Will try to make the verification errors nicer after 1.7. Any patches?
```

Original comment by `szcze...@gmail.com` on 11 Jan 2009 at 10:50

**Comment by GoogleCodeExporter** [comment]
```
I officially don't have time for this feature :) 

If anyone is keen on this feature, please submit a patch.
```

Original comment by `szcze...@gmail.com` on 22 Sep 2009 at 9:01
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I was bothered by this issue and I tried to create a patch that resolves it. 
Most of
the code is borrowed from MissingInvocationChecker and I would appreciate any 
feedback.
```

Original comment by `Krishnan...@gmail.com` on 21 Feb 2010 at 10:13

Attachments:
- [Issue_27.patch](https://storage.googleapis.com/google-code-attachments/mockito/issue-27/comment-10/Issue_27.patch)

**Comment by GoogleCodeExporter** [comment]
```
This is cool, thank you! I'm ready to merge your patch. Could you possibly 
write a
functional test that proves it (e.g. something that really shows the 
enhancement?)
```

Original comment by `szcze...@gmail.com` on 21 Feb 2010 at 2:49

**Comment by GoogleCodeExporter** [comment]
```
PS. If you kindly write the functional test I'm asking for please submit it as a
separate patch, ok?

Thank you :)
```

Original comment by `szcze...@gmail.com` on 21 Feb 2010 at 2:52

**Comment by GoogleCodeExporter** [comment]
```
Also, can you explain what you mean by new test 
'shouldReportArgumentsAreDifferent'.
It contains assertions and also it defines an expected exception. What is 
correct?
assertions or exception?
```

Original comment by `szcze...@gmail.com` on 21 Feb 2010 at 2:55

**Comment by GoogleCodeExporter** [comment]
```
Sorry about the typo. I had removed that earlier and but forgot to update the 
patch.
I am attaching the updated patch right now. In addition, I am attaching the
testng-results using Mockito distribution 1.8.2 for comparison. The third 
attachment
is the modification to WriterTest that was originally attached to the argument.

The results are as follows:

Method:testWriteInOrder
Argument(s) are different! Wanted:
outputStream.write(3);
-> at 
org.mockitousage.examples.use.WriterTest.testWriteInOrder(WriterTest.java:41)
Actual invocation has different arguments:
outputStream.write(4);
-> at org.mockitousage.examples.use.WriterTest.write(WriterTest.java:23)

Expected :outputStream.write(3);
Actual   :outputStream.write(4);

Method:testWriteInWrongOrder
org.mockito.exceptions.verification.VerificationInOrderFailure: 
Verification in order failure
Wanted but not invoked:
outputStream.write(4);
-> at 
org.mockitousage.examples.use.WriterTest.testWriteInWrongOrder(WriterTest.java:5
0)
Wanted anywhere AFTER following interaction:
outputStream.write([84, 101, 115, 116]);
-> at org.mockitousage.examples.use.WriterTest.write(WriterTest.java:24)

Method:testWriteInWrongOrder_string
org.mockito.exceptions.verification.VerificationInOrderFailure: 
Verification in order failure
Wanted but not invoked:
outputStream.write([88, 89, 90]);
-> at
org.mockitousage.examples.use.WriterTest.testWriteInWrongOrder_string(WriterTest
.java:58)
Wanted anywhere AFTER following interaction:
outputStream.write(4);
-> at org.mockitousage.examples.use.WriterTest.write(WriterTest.java:23)

Method:testWrite
Argument(s) are different! Wanted:
outputStream.write(3);
-> at org.mockitousage.examples.use.WriterTest.testWrite(WriterTest.java:64)
Actual invocation has different arguments:
outputStream.write(4);
-> at org.mockitousage.examples.use.WriterTest.write(WriterTest.java:23)

Expected :outputStream.write(3);
Actual   :outputStream.write(4);
```

Original comment by `Krishnan...@gmail.com` on 22 Feb 2010 at 7:53

Attachments:
- [Issue_27_v2.patch](https://storage.googleapis.com/google-code-attachments/mockito/issue-27/comment-14/Issue_27_v2.patch)
- [testng-results_with_mockito_dist.xml](https://storage.googleapis.com/google-code-attachments/mockito/issue-27/comment-14/testng-results_with_mockito_dist.xml)
- [WriterTest.java](https://storage.googleapis.com/google-code-attachments/mockito/issue-27/comment-14/WriterTest.java)

**Comment by GoogleCodeExporter** [comment]
```
Hi, Szczepan, 

Did you get a chance to review my updated patch?

Thanks,

Kartik
```

Original comment by `Krishnan...@gmail.com` on 24 Feb 2010 at 6:35

**Comment by GoogleCodeExporter** [comment]
```
This issue was closed by revision r1862.
```

Original comment by `szcze...@gmail.com` on 24 Feb 2010 at 10:37
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Hey, look at the changes with the revision -
DescriptiveMessagesOnVerificationInOrderErrorsTest.java contain the functional 
test I
was thinking about.

Thanks a lot for the patch!
```

Original comment by `szcze...@gmail.com` on 24 Feb 2010 at 10:41

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 28 Feb 2010 at 9:04
- Added labels: **Milestone-Release1.8.3**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 28 Feb 2010 at 9:09
- Changed title: **InOrder.verify() displays the actual invocation on error when arguments are different**
