### ISSUE TITLE
ConcurrentModificationExcception in verify(...) in multithreaded environment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#35]
```
What steps will reproduce the problem?

Can't easily reproduce, but encounter multiple times (from time to time, 
as usually with synchronization problems).

What is the expected output? What do you see instead?

ConcurrentModificationException is thrown:
java.util.ConcurrentModificationException
at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:761)
at java.util.LinkedList$ListItr.next(LinkedList.java:696)
at org.mockito.internal.util.ListUtil.filter(ListUtil.java:14)
at org.mockito.internal.verification.RegisteredInvocations.getAll
(RegisteredInvocations.java:29)
at org.mockito.internal.MockHandler.intercept(MockHandler.java:71)
at org.mockito.internal.creation.MethodInterceptorFilter.intercept
(MethodInterceptorFilter.java:45)
at 
cern.pm.core.srv.session.AnalysisSessionScheduler$$EnhancerByCGLIB$$784759c
1.newPmDataAvailable()
at 
cern.pm.core.srv.session.impl.AnalysisSessionStateImplTest.testDataCollecti
onFinished2(AnalysisSessionStateImplTest.java:144)

What version of the product are you using? On what operating system?

Mockito 1.6, Windows XP

Please provide any additional information below.

The code template which produces the exception looks like this:

InterfaceToMock interfaceToMock = mock(InterfaceToMock.class);
classUndertest.setInterfaceToMock (interfaceToMock );
classUndertest.doSomething();   //asynchronous call of interfaceToMock
Thread.sleep(500);
verify(interfaceToMock, times(1)).methodCalled();   //exception!
```

Original issue reported on code.google.com by `Roman.Go...@gmail.com` on 10 Nov 2008 at 10:37

**Comment by GoogleCodeExporter** [comment]
```
looking at it
```

Original comment by `szcze...@gmail.com` on 11 Nov 2008 at 7:20

**Comment by GoogleCodeExporter** [comment]
```
fixed in trunk. Thanks for submitting this bug!
```

Original comment by `szcze...@gmail.com` on 11 Nov 2008 at 9:08

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 12 Nov 2008 at 11:23
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 14 Jan 2009 at 10:48
- Added labels: **Milestone-Release1.7**
