### ISSUE TITLE
Wanted but not invoked exception in setup when running tests as a suite.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#36]
```
What steps will reproduce the problem?
1. see attached file. tests pass when run individually but fail when run as
a suite.

What is the expected output? What do you see instead?
expected output is two successful tests, actual output is:
first test: LuceneSearcherTest passes
second test: FeaturePagedResultTest fails on setup with exception:

org.mockito.exceptions.verification.WantedButNotInvoked: 
Wanted but not invoked:
query.setFirstResult(<any>);
    at
mockitobroketest.FeaturePagedResultTest.setup(FeaturePagedResultTest.java:18)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:122)
    at
org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadi
e.java:86)
    at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
    at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
    at
org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.
java:88)
    at
org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:5
1)
    at
org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)
    at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
    at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
    at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)
    at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReferen
ce.java:45)
    at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:460)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner
.java:673)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java
:386)
    at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.jav
a:196)




What version of the product are you using? On what operating system?
lucene 2.3.0
hibernate 3.2.6ga
mockito-all-1.6

Please provide any additional information below.


```

Original issue reported on code.google.com by `jscott...@gmail.com` on 26 Nov 2008 at 11:58

Attachments:
- [mockitobroketest.zip](https://storage.googleapis.com/google-code-attachments/mockito/issue-36/comment-0/mockitobroketest.zip)

**Comment by GoogleCodeExporter** [comment]
```
Hi,

It's because close() method is final so mockito cannot deal with it.
http://lucene.apache.org/java/2_1_0/api/org/apache/lucene/index/IndexReader.html
#close()

Mockito is doing pretty bad in telling you what's the real problem. I'm looking 
into
making the exception nicer.
```

Original comment by `szcze...@gmail.com` on 27 Nov 2008 at 12:26

**Comment by GoogleCodeExporter** [comment]
```
I mention about final methods in exception messages and I made sure "framework
validation" is done as often as possible so the exception should be much 
earlier + it
will be more descriptive. This is in trunk.
```

Original comment by `szcze...@gmail.com` on 11 Dec 2008 at 11:55
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 14 Jan 2009 at 10:48
- Added labels: **Milestone-Release1.7**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 14 Jan 2009 at 10:58
- Changed state: **Duplicate**
