### ISSUE TITLE
Stack trace filtering doesn't filter dexmaker classes on Android

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#360]
```
Mockito's awesome this-is-where-you-goofed error messages pick the wrong line 
numbers on Android because stack trace filtering is cglib-specific. The message 
includes a bogus InvocationHandlerAdapter.java source:

     [exec] Error in testUnexpectedCall:
     [exec] org.mockito.exceptions.verification.NoInteractionsWanted: 
     [exec] No interactions wanted here:
     [exec] -> at com.google.dexmaker.mockitoexample.MockitoExampleActivityTest.testUnexpectedCall(MockitoExampleActivityTest.java:36)
     [exec] But found this interaction:
     [exec] -> at com.google.dexmaker.mockito.InvocationHandlerAdapter.invoke(InvocationHandlerAdapter.java:54)
     [exec] Actually, above is the only interaction with this mock.
     [exec]     at com.google.dexmaker.mockitoexample.MockitoExampleActivityTest.testUnexpectedCall(MockitoExampleActivityTest.java:36)

What we really want is the actual application code:

     [exec] Error in testUnexpectedCall:
     [exec] org.mockito.exceptions.verification.NoInteractionsWanted: 
     [exec] No interactions wanted here:
     [exec] -> at com.google.dexmaker.mockitoexample.MockitoExampleActivityTest.testUnexpectedCall(MockitoExampleActivityTest.java:36)
     [exec] But found this interaction:
     [exec] -> at com.google.dexmaker.mockitoexample.MockitoExampleActivityTest.testUnexpectedCall(MockitoExampleActivityTest.java:34)
     [exec] Actually, above is the only interaction with this mock.
     [exec]     at com.google.dexmaker.mockitoexample.MockitoExampleActivityTest.testUnexpectedCall(MockitoExampleActivityTest.java:36)

I've attached a patch that fixes stack trace filtering for Android.

```

Original issue reported on code.google.com by `limpbizkit` on 28 Jul 2012 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
Attached the right patch.
```

Original comment by `limpbizkit` on 28 Jul 2012 at 6:34

Attachments:
- [stacktracefilter.patch](https://storage.googleapis.com/google-code-attachments/mockito/issue-360/comment-1/stacktracefilter.patch)

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the patch!

One thing I don't like is that mockito is decoupled from dexmaker via an 
extension point but coupled with dexmaker-specific stack trace filtering logic. 
OTOH, it indeed feels low risk. I'll think about it a bit more, maybe I'll 
patch a quick plugin and push out rc-2 to test it out.
```

Original comment by `szcze...@gmail.com` on 28 Jul 2012 at 6:50

**Comment by GoogleCodeExporter** [comment]
```
Friendly ping!
```

Original comment by `limpbizkit` on 11 Sep 2012 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Sorry we have been "busy" with summer time. Szczepan worked on something on 
that matter, you can take a look at this changeset n particular : 
http://code.google.com/p/mockito/source/detail?r=15f5c19aba7c473cf859c9cc80114dd
5547ac4f4&name=release
```

Original comment by `brice.du...@gmail.com` on 12 Sep 2012 at 8:28

**Comment by GoogleCodeExporter** [comment]
```
Totally missed that. Thanks guys.
```

Original comment by `limpbizkit` on 12 Sep 2012 at 3:13

**Comment by GoogleCodeExporter** [comment]
```
:)
If that's working for you, it will be included in the next release.

Cheers,
Brice
```

Original comment by `brice.du...@gmail.com` on 12 Sep 2012 at 3:53

**Comment by GoogleCodeExporter** [comment]
```
@limpbizkit, can you try out StackTraceCleanerProvider API and let us know if 
it would work?
```

Original comment by `szcze...@gmail.com` on 16 Sep 2012 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
It works! Thanks again.
https://code.google.com/p/dexmaker/source/detail?r=e65aa027cf7bd68ec13a27e0e05d9
d8d0f03aa20
```

Original comment by `limpbizkit` on 19 Sep 2012 at 3:56

**Comment by GoogleCodeExporter** [comment]
```
Oh right :) I'll get the release going then. Thanks for feedback!
```

Original comment by `szcze...@gmail.com` on 19 Sep 2012 at 5:43

**Comment by GoogleCodeExporter** [comment]
```
Fantastic!
```

Original comment by `limpbizkit` on 19 Sep 2012 at 5:44

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 6 Oct 2012 at 8:34
- Added labels: **Milestone-Release1.9.5**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 6 Oct 2012 at 8:34
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 19 Dec 2012 at 10:59
- Added labels: **Dexmaker-Android**
