### ISSUE TITLE
Deep Stubs are not serializable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#399]
```
What steps will reproduce the problem?
import org.junit.Test;
import org.mockito.Matchers;
import org.mockito.Mockito;

import java.io.ByteArrayOutputStream;
import java.io.ObjectOutputStream;
import java.util.Map;

public class DeepStubsAreNotSerializableTest {

  @Test
  public void name() throws Exception {
    Map map = Mockito.mock(Map.class, Mockito.RETURNS_DEEP_STUBS);

    Mockito.when(map.entrySet().contains(Matchers.anyString())).thenReturn(false);

    ByteArrayOutputStream serialized = new ByteArrayOutputStream();
    new ObjectOutputStream(serialized).writeObject(map);
  }
}

What is the expected output? What do you see instead?
java.io.NotSerializableException: 
org.mockito.internal.stubbing.defaultanswers.ReturnsDeepStubs$1
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1180)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
        ...

Please use labels and text to provide additional information.
Mockito 1.9.5, and earlier versions
```

Original issue reported on code.google.com by `brice.du...@gmail.com` on 19 Nov 2012 at 10:02

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 27 Nov 2012 at 5:07
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 27 Nov 2012 at 5:08
- Added labels: **Serialization**

**Comment by GoogleCodeExporter** [comment]
```
Have you been working on that or is it possible to start this one?
```

Original comment by `marcin.g...@gmail.com` on 23 Dec 2013 at 7:49

**Comment by GoogleCodeExporter** [comment]
```
You can start this one, but it's gonna be a challenging one, as it involves 
some new code regarding generics.

Anyway ou can still work on serialization when generics are not involved. 
That'll be very helpful.

And if you feel to do the complete job that will be even more awesome. Also 
feel free to discuss the design with me as the generics discovery code is kind 
of tricky.
```

Original comment by `brice.du...@gmail.com` on 24 Dec 2013 at 11:26

**Comment by GoogleCodeExporter** [comment]
```
Ok - thought that it will be faster ;) Will try to work on this in free time.
```

Original comment by `marcin.g...@gmail.com` on 24 Dec 2013 at 11:29

**Comment by GoogleCodeExporter** [comment]
```
PR for the non generic work - https://github.com/mockito/mockito/pull/30
```

Original comment by `marcin.g...@gmail.com` on 27 Dec 2013 at 12:37

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 24 Aug 2014 at 3:48
- Changed state: **Fixed**
- Added labels: **Milestone-Release1.10.0**
