### ISSUE TITLE
Error Message org.mockito.internal.progress.SequenceNumber

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#407]
```
Adhoc basis we are getting the below exception. Please let me know in which 
situation the error messages will come.

Stacktrace
java.lang.LinkageError: org.mockito.internal.progress.SequenceNumber
    at java.lang.ClassLoader.defineClassImpl(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:258)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:195)
    at org.powermock.core.classloader.MockClassLoader.loadUnmockedClass(MockClassLoader.java:190)
    at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:148)
    at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:65)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:597)
    at org.powermock.api.mockito.internal.invocationcontrol.MockitoMethodInvocationControl.performIntercept(MockitoMethodInvocationControl.java:257)
    at org.powermock.api.mockito.internal.invocationcontrol.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:193)
    at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:105)
    at org.powermock.core.MockGateway.methodCall(MockGateway.java:60)


```

Original issue reported on code.google.com by `j.prakas...@gmail.com` on 19 Dec 2012 at 5:02

**Comment by GoogleCodeExporter** [comment]
```
Hi,

LinkageError is usually an issue that appear when two version of the library in 
the classpath. You should check that.

Cheers,
Brice
```

Original comment by `brice.du...@gmail.com` on 19 Dec 2012 at 10:49

**Comment by GoogleCodeExporter** [comment]
Original comment by `brice.du...@gmail.com` on 16 Jan 2013 at 7:18
- Changed state: **Invalid**
