### ISSUE TITLE
Framework validation produces confusing results

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#54]
```
What steps will reproduce the problem?
1. Execute 1 test with a bare verify(mock) call at the end. 
2. Execute another test that uses mockito correctly.

What is the expected output? What do you see instead?

I expect the validation to point you to the first test; the test which is
doing the wrong thing.  Instead, though it produces the correct message,
it's the second test that fails.  To add insult to injury, the first test
actually passes.

Output:
org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Previous verify(mock) doesn't have a method call!
Example of correct verification:
    verify(mock).doSomething()
Also make sure the method is not final - you cannot verify final methods.
org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Previous verify(mock) doesn't have a method call!
Example of correct verification:
    verify(mock).doSomething()
Also make sure the method is not final - you cannot verify final methods.
    at
org.foo.conversion.pdf.command.PDFToHTMLTest.setUp(PDFToHTMLTest.java:35)   
    at junit.framework.TestCase.runBare(TestCase.java:128)
    at junit.framework.TestResult$1.protect(TestResult.java:106)
    at junit.framework.TestResult.runProtected(TestResult.java:124)
    at junit.framework.TestResult.run(TestResult.java:109)
    at junit.framework.TestCase.run(TestCase.java:120)
    at junit.framework.TestSuite.runTest(TestSuite.java:230)
    at junit.framework.TestSuite.run(TestSuite.java:225)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at org.apache.maven.surefire.junit.JUnitTestSet.execute(JUnitTestSet.java:213)
    at
org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(Abstra
ctDirectoryTestSuite.java:140)
    at
org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirec
toryTestSuite.java:127)
    at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:585)
    at
org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBoote
r.java:338)
    at
org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:997)

What version of the product are you using? On what operating system?
Mockito 1.7
WinXP
Tests ran using both IntelliJ IDEA test runner and Maven surefire.

Please provide any additional information below.
FYI I'm new to Mockito, and like what I see so far apart from this problem.
 I spent pretty much all afternoon trying to figure out why my test was
failing, when in fact it was someone else's test that was the problem.  I
realize the message says the *previous* verify(mock), but that's easy to
miss and not much help anyway when you don't know what order the tests are
run in.

```

Original issue reported on code.google.com by `twbec...@gmail.com` on 12 Feb 2009 at 9:18

**Comment by GoogleCodeExporter** [comment]
```
I think you're right. I'll try to make the exception nicer and point out the 
line of
code where the framework was misused.

Thanks for submitting this suggestion and sorry for your wasted afternoon!
```

Original comment by `szcze...@gmail.com` on 13 Feb 2009 at 7:05

**Comment by GoogleCodeExporter** [comment]
```
You're gonna like my latest check-in.

Now you should see where verify() was improperly called. If you find some time 
you
may want to check it out and tell me if this is something you wanted.

I'm going to add similar feature for other actions that misuse the framework

Fixed in trunk.
```

Original comment by `szcze...@gmail.com` on 13 Feb 2009 at 11:14
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
Thanks a lot, I'll be sure to look into it.  Overall I like the idea of the 
messages,
they did help me once when I had a problem in my test.  I'm just not sure it is 
worth
the tradeoff if it produces confusing situations like what I saw.  Thanks again.
```

Original comment by `twbec...@gmail.com` on 13 Feb 2009 at 1:12

**Comment by GoogleCodeExporter** [comment]
```
So, I checked out trunk, and it definitely is an improvement.  What I still 
can't get
past though is this:  The test that is using mockito improperly passes, and the
subsequent test fails.  Although the message now makes it clearer where the 
problem
actually is, it still comes down to test B fails due to a problem in test A, 
which is
completely antithetical to independent unit tests.  Consider the following 
scenario:

public void testA() {
  private Foo mock = mock(Foo.class);
  ...
  ...
  verify(mock);  <- problem is here though is not caught; test passes.  When run by
itself in an IDE for example there's no indication there's a problem.
}

public void testB() {
  private Bar mock = mock(Bar.class)  <- problem is not caught until here, this test
fails.  This test may well even be in a different class.

}

What I'm wondering is if it is somehow possible for Mockito to verify itself 
after
each test executes, rather than just the next time you call into the framework 
(which
may be in a different test as shown here).  

```

Original comment by `twbec...@gmail.com` on 13 Feb 2009 at 3:23

**Comment by GoogleCodeExporter** [comment]
```
validate() is something we can put in our JUnitRunner, let's say somewhere in
tearDown(). However, if you don't use the runner then you still have the 
problem that
the wrong test fails. 

We can provide a method a la Mockito.validateFramework() but then I don't know 
if the
users would like to pollute their tearDowns() with it.

> antithetical to independent unit tests

You're right but the alternative is no better: the user doesn't know his test 
is not
correct.
```

Original comment by `szcze...@gmail.com` on 13 Feb 2009 at 3:42

**Comment by GoogleCodeExporter** [comment]
```
"validate() is something we can put in our JUnitRunner, let's say somewhere in
tearDown(). However, if you don't use the runner then you still have the 
problem that
the wrong test fails. 

We can provide a method a la Mockito.validateFramework() but then I don't know 
if the
users would like to pollute their tearDowns() with it."


I would vote for both of those changes.  While they don't eliminate the 
problem, they
reduce it.  Users may already have some sort of superclass in which they call
MockitoAnnotations.initMocks() in order to enable @Mock annotations.  If so, 
they can
go ahead and put the validateFramework() call in that class's tearDown().  As it
stands, we don't have that option.

"You're right but the alternative is no better: the user doesn't know his test 
is not
correct."  

True but he already "knows" it is correct when he runs it in his IDE and it 
passes. 
Only when another test is run subsequent to it is the user given any indication
there's a problem.  Just food for thought.  Thanks a lot for your efforts on 
Mockito!



```

Original comment by `twbec...@gmail.com` on 13 Feb 2009 at 5:38

**Comment by GoogleCodeExporter** [comment]
```
> I would vote for both of those changes

Ok, I'll try to make it happen :)

>True but he already "knows" it is correct when he runs it in his IDE and it 
passes. 
>Only when another test is run subsequent to it is the user given any indication
>there's a problem.

ok, so you don't think Mockito should validate every time the user interacts 
with the
framework?
```

Original comment by `szcze...@gmail.com` on 14 Feb 2009 at 11:14
- Changed state: **New**

**Comment by GoogleCodeExporter** [comment]
```
"ok, so you don't think Mockito should validate every time the user interacts 
with the
framework?"

In principle I think it's a good idea, and the error messages are helpful.  
It's just
unfortunate that you can't catch errors made in call N until call N+1, which of
course isn't guaranteed to happen.  

I very much like the idea of a validateFramework() call that folks can 
deliberately
put in to ensure this happens and happens where they want it to.  If you add 
this
method, does the framework still need to automatically validate?  That's up to 
you. 
Some documentation/FAQs around the edge cases where the automatic validation 
doesn't
happen or doesn't do what you expect would probably be all that's needed.     



```

Original comment by `twbec...@gmail.com` on 14 Feb 2009 at 3:14

**Comment by GoogleCodeExporter** [comment]
```
Yeah, I'm thinking about some kind of troubleshooting wiki page. 

Thanks for your suggestions!
```

Original comment by `szcze...@gmail.com` on 14 Feb 2009 at 6:21

**Comment by GoogleCodeExporter** [comment]
```
Related to issue 66.

I'm closing this one. There are number of features in trunk version that makes 
the
problem vanish.

1. All framework validation problems now have the exception message that 
contains
a navigable (clickable) location of the defect.

2. There is a new MockitoTroubleshooter class that currently enables user to
validate the framework state explicitly. This might be helpful for debugging 
some
corner cases and for some eager users who wish to validate the state after each 
test.
Bear in mind that Mockito validates the framework state every time you use it. 
You
can read more in javadoc for MockitoTroubleshooter class:
http://code.google.com/p/mockito/source/browse/trunk/src/org/mockito/MockitoTrou
bleshooter.java

3. There's also a section in FAQ that explains framework validation stuff. (Let 
me
know if it makes sense)
```

Original comment by `szcze...@gmail.com` on 21 Apr 2009 at 10:14
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 9 Jun 2009 at 3:15
- Added labels: **Milestone-Release1.8**
