### ISSUE TITLE
Using Mockito with Android virtual machine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dlsgusrn7577/mockito#57]
```
I get the following exception trying to create a mock inside the Android
Dalvik JVM.  I'm using mockito-all-1.7 (though the same excepiton comes
from mockito-all-1.6).  the class I'm mocking does not extend any Android
class or implement any Android interface.

The problem can be recreated by trying to instantiate a mock when the test
is run using the Android SDK utility "adb shell am instrument ..."

java.lang.ExceptionInInitializerError
    at
org.mockito.internal.creation.jmock.ClassImposterizer.createProxyClass(ClassImpo
sterizer.java:75)
    at
org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposteri
zer.java:57)
    at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:27)
    at org.mockito.Mockito.mock(Mockito.java:561)
    at org.mockito.Mockito.mock(Mockito.java:514)
    at
com.wilson.android.library.BookServiceFetchingHandlerTest.testHandleMessage_Show
sDialog_ForException(BookServiceFetchingHandlerTest.java:28)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:155)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:142)
    at
android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:31
3)
    at
android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1508)
Caused by: java.lang.VerifyError: org.mockito.cglib.core.ReflectUtils
    at
org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:166)
    at
org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrateg
y.java:25)
    at
org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java
:216)
    at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
    at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:116)
    at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:108)
    at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:104)
    at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
    ... 18 more




```

Original issue reported on code.google.com by `jw.ma...@gmail.com` on 15 Feb 2009 at 1:57

**Comment by GoogleCodeExporter** [comment]
```
Hi, can you attach a zip with all required jars & the failing example?
```

Original comment by `szcze...@gmail.com` on 15 Feb 2009 at 4:04

**Comment by GoogleCodeExporter** [comment]
```
I can try to put something together.  It's going to be involved.  The Android 
SDK
includes the SDK - no Android phone is required.
```

Original comment by `jw.ma...@gmail.com` on 17 Feb 2009 at 1:00

**Comment by GoogleCodeExporter** [comment]
```
Ok, I'm downloading the SDK and will try to reproduce it.
```

Original comment by `szcze...@gmail.com` on 19 Feb 2009 at 7:19

**Comment by GoogleCodeExporter** [comment]
```
Here is a tar of an eclipse project that you can sync to the emulator.  You 
should be
able to import this project into an eclipse installation that has the android 
plugin.
 Then run "run as... Android Application" will push the files to the emulator.  once
that's done, the adbtest.sh script will execute the test inside the emulator, 
sending
the error to stdout.
```

Original comment by `jw.ma...@gmail.com` on 19 Feb 2009 at 1:43

Attachments:
- [ExampleAndroidTest.tgz](https://storage.googleapis.com/google-code-attachments/mockito/issue-57/comment-4/ExampleAndroidTest.tgz)

**Comment by GoogleCodeExporter** [comment]
```
Thanks, we'll look at it. From the way you run it I guess it's executed on 
different
than usual jvm. This might be the problem.
```

Original comment by `szcze...@gmail.com` on 22 Feb 2009 at 12:07

**Comment by GoogleCodeExporter** [comment]
```
That's right, it is a different JVM named Dalvik.
```

Original comment by `jw.ma...@gmail.com` on 22 Feb 2009 at 4:07

**Comment by GoogleCodeExporter** [comment]
```
I can't get through the last step. When I execute the script here is what 
happens:

C:\projects\debugging\ExampleAndroidTest>adb shell am instrument -w -e class exa
mple.android.test.BarTest example.android.test/android.test.InstrumentationTestR
unner
INSTRUMENTATION_FAILED: example.android.test/android.test.InstrumentationTestRun
ner
usage: am [start|broadcast|instrument]
       am start -D INTENT
       am broadcast INTENT
       am instrument [-r] [-e <ARG_NAME> <ARG_VALUE>] [-p <PROF_FILE>]
                [-w] <COMPONENT>

       INTENT is described with:
                [-a <ACTION>] [-d <DATA_URI>] [-t <MIME_TYPE>]
                [-c <CATEGORY> [-c <CATEGORY>] ...]
                [-e|--es <EXTRA_KEY> <EXTRA_STRING_VALUE> ...]
                [--ez <EXTRA_KEY> <EXTRA_BOOLEAN_VALUE> ...]
                [-e|--ei <EXTRA_KEY> <EXTRA_INT_VALUE> ...]
                [-n <COMPONENT>] [-f <FLAGS>] [<URI>]

```

Original comment by `szcze...@gmail.com` on 26 Feb 2009 at 10:20

**Comment by GoogleCodeExporter** [comment]
```
it looks like the usage error is a red herring.  I uninstalled the package from 
my
Emulator and got the same error.  So my guess to your problem is that you still 
need
to install the project to the emulator.  If you right click on the project and 
choose
"Run As -> Android Application" you should see a series of log messages in the
Android Console ending in the following:
   [2009-02-26 21:21:40 - ExampleAndroidTest] Installing ExampleAndroidTest.apk...
   [2009-02-26 21:21:44 - ExampleAndroidTest] Success!
   [2009-02-26 21:21:44 - ExampleAndroidTest]
/ExampleAndroidTest/bin/ExampleAndroidTest.apk installed on device
   [2009-02-26 21:21:44 - ExampleAndroidTest] Done!
```

Original comment by `jw.ma...@gmail.com` on 27 Feb 2009 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
Thanks for helping out with getting this issue reproduced!

> "Run As -> Android Application" 

Yes, I got it working -> it's all good I can see "[2009-02-27 09:53:26 -
ExampleAndroidTest] Done!" message. I have the emulator working in eclipse so I 
start
up the script in the command line. It fails with the error - see error log in my
previous entry - INSTRUMENTATION_FAILED stuff.
```

Original comment by `szcze...@gmail.com` on 27 Feb 2009 at 11:14

**Comment by GoogleCodeExporter** [comment]
```
We can try some basic stuff to sniff out the problem:

1) run "adb devices" - the output should be your running emulator.  It's 
usually:
     emulator-5554  device
2) run "adb shell pm list packages" - make sure the output contains the package
package:example.android.test
```

Original comment by `jw.ma...@gmail.com` on 28 Feb 2009 at 12:02

**Comment by GoogleCodeExporter** [comment]
```
I cannot work on it at the moment - I'm off for holidays for about a month. I 
asked a
colleague to look at it but I don't when he does it. You might grab the sources 
and
try to fix it if you feel like :)
```

Original comment by `szcze...@gmail.com` on 28 Feb 2009 at 6:05

**Comment by GoogleCodeExporter** [comment]
```
This won't go the next release - we don't even know if it is fixable because it 
is a
runtime problem on different kind of virtual machine. Will get back to it once 
we
have time.

If there's a developer who knows android enough and is not afraid of some 
debugging
sessions with Mockito - go kill this bug :)
```

Original comment by `szcze...@gmail.com` on 21 Apr 2009 at 10:16
- Added labels: **Priority-Low**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
Original comment by `szcze...@gmail.com` on 2 May 2009 at 8:31
- Changed title: **Using Mockito with Android virtual machine**

**Comment by GoogleCodeExporter** [comment]
```
I have a hunch that this is not Mockito related.  I hope to have some more time 
to
finish tracing it down.
```

Original comment by `jw.ma...@gmail.com` on 7 May 2009 at 2:30

**Comment by GoogleCodeExporter** [comment]
```
It would be great. Thank you!
```

Original comment by `szcze...@gmail.com` on 7 May 2009 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
I'm closing this one as apparently no one has time for it. Most likely it's an 
issue
with different vm.
```

Original comment by `szcze...@gmail.com` on 22 Sep 2009 at 9:03
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
There is useful information about mocking on Dalvik from some Googlers here -
https://sites.google.com/site/androiddevtesting/
```

Original comment by `theosda...@googlemail.com` on 24 Oct 2009 at 8:42
